In [1]:
from bbml.foundations.gpt2 import GPT2Foundation, GPTConfig

In [2]:
foundation = GPT2Foundation(
    GPTConfig(),
    None
)

loading weights from pretrained gpt: gpt2
forcing vocab_size=50257, block_size=1024, bias=True
number of parameters: 123.65M


In [37]:
named_modules = {k:v for k,v in foundation.named_modules()}
named_modules

{'': GPT2Foundation(
   (model): GPT(
     (transformer): ModuleDict(
       (wte): Embedding(50257, 768)
       (wpe): Embedding(1024, 768)
       (drop): Dropout(p=0.0, inplace=False)
       (h): ModuleList(
         (0-11): 12 x Block(
           (ln_1): LayerNorm()
           (attn): CausalSelfAttention(
             (c_attn): Linear(in_features=768, out_features=2304, bias=True)
             (c_proj): Linear(in_features=768, out_features=768, bias=True)
             (attn_dropout): Dropout(p=0.0, inplace=False)
             (resid_dropout): Dropout(p=0.0, inplace=False)
           )
           (ln_2): LayerNorm()
           (mlp): MLP(
             (c_fc): Linear(in_features=768, out_features=3072, bias=True)
             (gelu): GELU(approximate='none')
             (c_proj): Linear(in_features=3072, out_features=768, bias=True)
             (dropout): Dropout(p=0.0, inplace=False)
           )
         )
       )
       (ln_f): LayerNorm()
     )
     (lm_head): Linear(in_featur

In [4]:
from torch import nn


[print(n) for n,m in named_modules.items() if isinstance(m, nn.Linear)]
pass

model.transformer.h.0.attn.c_attn
model.transformer.h.0.attn.c_proj
model.transformer.h.0.mlp.c_fc
model.transformer.h.0.mlp.c_proj
model.transformer.h.1.attn.c_attn
model.transformer.h.1.attn.c_proj
model.transformer.h.1.mlp.c_fc
model.transformer.h.1.mlp.c_proj
model.transformer.h.2.attn.c_attn
model.transformer.h.2.attn.c_proj
model.transformer.h.2.mlp.c_fc
model.transformer.h.2.mlp.c_proj
model.transformer.h.3.attn.c_attn
model.transformer.h.3.attn.c_proj
model.transformer.h.3.mlp.c_fc
model.transformer.h.3.mlp.c_proj
model.transformer.h.4.attn.c_attn
model.transformer.h.4.attn.c_proj
model.transformer.h.4.mlp.c_fc
model.transformer.h.4.mlp.c_proj
model.transformer.h.5.attn.c_attn
model.transformer.h.5.attn.c_proj
model.transformer.h.5.mlp.c_fc
model.transformer.h.5.mlp.c_proj
model.transformer.h.6.attn.c_attn
model.transformer.h.6.attn.c_proj
model.transformer.h.6.mlp.c_fc
model.transformer.h.6.mlp.c_proj
model.transformer.h.7.attn.c_attn
model.transformer.h.7.attn.c_proj
model.tr

In [5]:
[print(m) for m in named_modules.keys()]
pass


model
model.transformer
model.transformer.wte
model.transformer.wpe
model.transformer.drop
model.transformer.h
model.transformer.h.0
model.transformer.h.0.ln_1
model.transformer.h.0.attn
model.transformer.h.0.attn.c_attn
model.transformer.h.0.attn.c_proj
model.transformer.h.0.attn.attn_dropout
model.transformer.h.0.attn.resid_dropout
model.transformer.h.0.ln_2
model.transformer.h.0.mlp
model.transformer.h.0.mlp.c_fc
model.transformer.h.0.mlp.gelu
model.transformer.h.0.mlp.c_proj
model.transformer.h.0.mlp.dropout
model.transformer.h.1
model.transformer.h.1.ln_1
model.transformer.h.1.attn
model.transformer.h.1.attn.c_attn
model.transformer.h.1.attn.c_proj
model.transformer.h.1.attn.attn_dropout
model.transformer.h.1.attn.resid_dropout
model.transformer.h.1.ln_2
model.transformer.h.1.mlp
model.transformer.h.1.mlp.c_fc
model.transformer.h.1.mlp.gelu
model.transformer.h.1.mlp.c_proj
model.transformer.h.1.mlp.dropout
model.transformer.h.2
model.transformer.h.2.ln_1
model.transformer.h.2.att

In [7]:
import re

re_attn_c_attn = '.*\.attn\.c_attn$'

matches = {}
for name, module in named_modules.items():
    result = re.match(re_attn_c_attn, name)
    if result is not None:
        matches[name] = module
    
matches

<>:3: SyntaxWarning: invalid escape sequence '\.'
<>:3: SyntaxWarning: invalid escape sequence '\.'
/var/folders/v0/dlhfhpj533b4_ldsv6gq0q8h0000gn/T/ipykernel_21503/300406542.py:3: SyntaxWarning: invalid escape sequence '\.'
  re_attn_c_attn = '.*\.attn\.c_attn$'


{'model.transformer.h.0.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.1.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.2.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.3.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.4.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.5.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.6.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.7.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.8.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.9.attn.c_attn': Linear(in_features=768, out_features=2304, bias=True),
 'model.transformer.h.10.attn.c_attn': Linear(in_features=768, out_fea

In [8]:
c_attn = matches["model.transformer.h.0.attn.c_attn"]

In [9]:
import torch

x = torch.rand((1,10,768))

In [10]:
n_head: int = 12
n_embd: int = 768

B, T, C = x.size()

q, k, v  = c_attn(x).split(n_embd, dim=2)
headsk = k.view(B, T, n_head, C // n_head).transpose(1, 2) # (B, nh, T, hs)
headsq = q.view(B, T, n_head, C // n_head).transpose(1, 2) # (B, nh, T, hs)
headsv = v.view(B, T, n_head, C // n_head).transpose(1, 2) # (B, nh, T, hs)

In [15]:
# split to just qkv
to_q = nn.Linear(n_embd, n_embd)
to_k = nn.Linear(n_embd, n_embd)
to_v = nn.Linear(n_embd, n_embd)

to_q.weight.data = c_attn.weight.data[0:n_embd,:]
to_q.bias.data = c_attn.bias.data[0:n_embd]
to_k.weight.data = c_attn.weight.data[n_embd:2*n_embd,:]
to_k.bias.data = c_attn.bias.data[n_embd:2*n_embd]
to_v.weight.data = c_attn.weight.data[2*n_embd:,:]
to_v.bias.data = c_attn.bias.data[2*n_embd:]


In [ ]:
torch.cat([to_q(x), to_k(x), to_v(x)], dim=-1) - c_attn(x)
# validate =0

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>)

In [ ]:
to_q(x) - q, to_k(x) - k, to_v(x) - v
# validate =0

(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>),
 tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>),
 tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>))

In [31]:
# split c_attn to qkv and heads
total_head_linears = 3 * n_head
head_dim = n_embd // n_head

heads = {
    "q": [],
    "k": [],
    "v": []
}

cur_ind = 0
for head_type in heads:
    for head_num in range(n_head):
        split_weight = c_attn.weight.data[cur_ind:cur_ind+head_dim,:]  # [out_dim, in_dim] -> [head_dim, in_dim]
        split_bias = c_attn.bias.data[cur_ind:cur_ind+head_dim]  # [out_dim] -> [head_dim]
        new_linear = nn.Linear(n_embd, head_dim)
        new_linear.weight.data = split_weight
        new_linear.bias.data = split_bias
        heads[head_type].append(new_linear)
        cur_ind += head_dim

In [ ]:

# get q
all_q = []
for qhead in heads["q"]:
    one_head_q = qhead(x)
    all_q.append(one_head_q)

each_head_q = torch.cat(all_q, dim=-1)
each_head_q.shape

torch.Size([1, 10, 768])

In [34]:
each_head_q - q

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>)

In [35]:

# get q
all_attn = []
for qhead in heads["q"]:
    one_head_q = qhead(x)
    all_attn.append(one_head_q)

for qhead in heads["k"]:
    one_head_k = qhead(x)
    all_attn.append(one_head_k)

for qhead in heads["v"]:
    one_head_v = qhead(x)
    all_attn.append(one_head_v)

each_head_attn = torch.cat(all_attn, dim=-1)
each_head_attn.shape

torch.Size([1, 10, 2304])

In [36]:
each_head_attn - c_attn(x)

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SubBackward0>)

# conf

In [86]:
%%writefile config.yaml
weight_types:
    attn_c_attn:
        pattern: '.*\.attn\.c_attn$'
        split: false  # qkv, heads
        qkv_order: qkv  # string
        n_head: 12
    attn_c_proj: 
        pattern: '.*\.attn\.c_proj$'
    mlp_c_fc: 
        pattern: '.*\.mlp\.c_fc$'
    mlp_c_proj: 
        pattern: '.*\.mlp\.c_proj$'

Overwriting config.yaml


In [1]:
import yaml
with open("config.yaml") as f:
    cfg = yaml.safe_load(f)

In [4]:
import re

patt = cfg['weight_types']["attn_c_attn"]["pattern"]
print(repr(patt))

re.match(patt, "model.transformer.h.0.attn.c_attn")

'.*\\.attn\\.c_attn$'


<re.Match object; span=(0, 33), match='model.transformer.h.0.attn.c_attn'>

In [ ]:

import math
from torch.nn import init
from torch.nn import functional as F


class SplitLinear(nn.Module):
    def __init__(self):
        super().__init__()
        self.splits: nn.Module|nn.Linear = []
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        outs = []
        for split in self.splits:
            outs = split(x)
        return torch.cat(outs, dim=-1)

class ShareLinear(nn.Module):
    def __init__(
        self,
        in_features: int,
        basis_features: int,
        out_features: int,
        bias: bool = True,
        device=None,
        dtype=None
    ):
        super().__init__()
        self.basis = nn.Parameter(
            torch.empty(basis_features, in_features, device=device, dtype=dtype)
        )
        self.coefficient = nn.Parameter(
            torch.empty(out_features, basis_features, device=device, dtype=dtype)
        )
        self.bias = nn.Parameter(
            torch.empty(out_features, device=device, dtype=dtype)
        )
        # self.original = nn.Parameter(
        #     torch.empty(basis_features, in_features, device=device, dtype=dtype)
        # )
    
    
    def initialize_parameters(self) -> None:
        # from nn.Linear
        init.kaiming_uniform_(self.basis, a=math.sqrt(5))
        init.kaiming_uniform_(self.coefficient, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            init.uniform_(self.bias, -bound, bound)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b = F.linear(x, self.basis)
        out = F.linear(b, self.coefficient, self.bias)
        return out

        

In [ ]:
from collections import defaultdict


class SplitLinearWrapper:
    def __init__(self, model, config):
        self.model = model
        self.config = config

        self.weight_types = defaultdict(list)

        named_modules = {k:v for k,v in model.named_modules()}

        for name, module in named_modules:
            for wtype, wtype_cfg in self.config["weight_types"].items():
                if re.match(wtype_cfg["pattern"], name) is not None:
                    name_parts = name.split(".")
                    parent_name = ".".join(name_parts[:-1])
                    parent = named_modules[parent_name]
                    list_id = None
                    if name_parts[-1].isdigit():
                        list_id = int(name_parts[-1])

                    self.weight_types[wtype].append({
                        "name": name,
                        "module": module,
                        "parent": parent,
                        "list_id": list_id,
                        "last_name_part": name_parts[-1],
                    })
        
        for wtype, list_wt_modules in self.weight_types.items():
            wtype_cfg = self.config["weight_types"][wtype]
            for wt_dict in list_wt_modules:
                module = wt_dict["module"]
                name = wt_dict["name"]
                if wtype_cfg["split"] == "qkv":
                    split_linear = SplitLinear()
                    in_feats = module.in_features
                    out_feats = module.out_features
                    assert out_feats % 3 == 0
                    qkv_feats = out_feats // 3 
                    
                    to_q = nn.Linear(in_feats, qkv_feats)
                    to_k = nn.Linear(in_feats, qkv_feats)
                    to_v = nn.Linear(in_feats, qkv_feats)

                    to_q.weight.data = module.weight.data[0:qkv_feats,:]
                    to_q.bias.data = module.bias.data[0:qkv_feats]
                    to_k.weight.data = module.weight.data[qkv_feats:2*qkv_feats,:]
                    to_k.bias.data = module.bias.data[qkv_feats:2*qkv_feats]
                    to_v.weight.data = module.weight.data[2*qkv_feats:,:]
                    to_v.bias.data = module.bias.data[2*qkv_feats:]

                    qkv = {
                        "q": to_q,
                        "k": to_k,
                        "v": to_v,
                    }
                    for n in wt_dict["qkv_order"]:
                        split_linear.splits.append(qkv[n])
                    setattr(wt_dict["parent"], wt_dict["last_name_part"], split_linear)

                elif wtype_cfg["split"] == "heads":
                    split_linear = SplitLinear()
                    in_feats = module.in_features
                    out_feats = module.out_features
                    assert out_feats % 3 == 0
                    qkv_feats = out_feats // 3 
                    n_heads = wtype_cfg["n_head"]

                    head_dim = qkv_feats // n_heads

                    heads = {
                        "q": [],
                        "k": [],
                        "v": []
                    }

                    cur_ind = 0
                    for head_type in heads:
                        for head_num in range(n_heads):
                            split_weight = module.weight.data[cur_ind:cur_ind+head_dim,:]  # [out_dim, in_dim] -> [head_dim, in_dim]
                            split_bias = module.bias.data[cur_ind:cur_ind+head_dim]  # [out_dim] -> [head_dim]
                            new_linear = nn.Linear(in_feats, head_dim)
                            new_linear.weight.data = split_weight
                            new_linear.bias.data = split_bias
                            heads[head_type].append(new_linear)
                            cur_ind += head_dim
                    
                    for n in wt_dict["qkv_order"]:
                        for head in heads[n]:
                            split_linear.splits.append(head)
                    
                    setattr(wt_dict["parent"], wt_dict["last_name_part"], split_linear)

                else: # no split
                    split_linear = SplitLinear()
                    in_linear = nn.Linear(module.in_features, module.out_features, bias=module.bias)
                    in_linear.weight.data = module.weight.data
                    if module.bias:
                        in_linear.bias.data = module.bias.data
                    split_linear.splits.append(in_linear)
                    setattr(wt_dict["parent"], wt_dict["last_name_part"], split_linear)
                    

In [2]:
import torch

torch.manual_seed(0)

# --- toy setup: one Linear layer ---
in_dim  = 64
out_dim = 48
n_calib = 512   # "calibration" samples (columns)

W = torch.randn(out_dim, in_dim)          # weight matrix (out_dim x in_dim)
X = torch.randn(in_dim, n_calib)          # activations (in_dim x n_calib)

# Original output
Y = W @ X                                  # (out_dim x n_calib)

# --- Cholesky-based whitening on X ---
# Gram / (unnormalized covariance) of features: G = X X^T
G = X @ X.T                                # (in_dim x in_dim)

eps = 1e-5
S = torch.linalg.cholesky(G + eps * torch.eye(in_dim))  # lower-triangular, G ≈ S S^T

# Whitened activations: Xw = S^{-1} X  (do NOT form S^{-1}; solve triangular system)
Xw = torch.linalg.solve_triangular(S, X, upper=False)   # solves S * Xw = X

# Check: Xw Xw^T ≈ I  (up to eps and finite-sample effects)
I = torch.eye(in_dim)
whiten_error = (Xw @ Xw.T - I).norm() / I.norm()
print("Relative ||Xw Xw^T - I||:", float(whiten_error))

# --- "whiten-then-SVD" compression: SVD on (W S) ---
WS = W @ S                                  # (out_dim x in_dim)

U, sig, Vh = torch.linalg.svd(WS, full_matrices=False)  # WS = U diag(sig) Vh

k = 30  # target rank
Uk  = U[:, :k]
sigk = sig[:k]
Vhk = Vh[:k, :]

# Low-rank approx of WS:  WS_hat = Uk diag(sigk) Vhk
WS_hat = (Uk * sigk) @ Vhk                  # (out_dim x in_dim)

# Using the factorized form directly: Y_hat = WS_hat @ Xw
Y_hat = WS_hat @ Xw

rel_err = (Y_hat - Y).norm() / Y.norm()
print(f"Whiten+SVD rank-{k} relative output error:", float(rel_err))

# --- If you want an explicit compressed weight matrix W_hat (so Y_hat = W_hat @ X) ---
# W_hat = WS_hat @ S^{-1}  (compute via triangular solve on transpose)
# Since W_hat^T = S^{-T} WS_hat^T, solve: (S^T) * W_hat^T = WS_hat^T
W_hat_T = torch.linalg.solve_triangular(S.T, WS_hat.T, upper=True)
W_hat = W_hat_T.T

Y_hat2 = W_hat @ X
print("Max |Y_hat - Y_hat2|:", float((Y_hat - Y_hat2).abs().max()))

# --- Baseline: plain SVD on W (no whitening), for comparison ---
U0, sig0, Vh0 = torch.linalg.svd(W, full_matrices=False)
W_hat0 = (U0[:, :k] * sig0[:k]) @ Vh0[:k, :]
Y_hat0 = W_hat0 @ X
rel_err0 = (Y_hat0 - Y).norm() / Y.norm()
print(f"Plain SVD rank-{k} relative output error:", float(rel_err0))

Relative ||Xw Xw^T - I||: 3.8652837019981234e-07
Whiten+SVD rank-30 relative output error: 0.24934543669223785
Max |Y_hat - Y_hat2|: 1.52587890625e-05
Plain SVD rank-30 relative output error: 0.2619509994983673


In [63]:

def compute_num_basis(
    in_features: int, out_features: int, group_size: int, compression_ratio: int
) -> int:
    """Compute number of basis vectors for target compression ratio."""
    total_original = in_features * out_features * group_size
    # Compressed size: in_features * num_basis + num_basis * out_features * group_size
    # Solving for num_basis given compression ratio
    num_basis = int(
        (total_original * compression_ratio) / (in_features + out_features * group_size)
    )
    return max(1, num_basis)

compute_num_basis(100, 100, 1, 0.9)

45

In [40]:
def compute_num_basis(features: int, group_size: int, compression_ratio: int):
    return (compression_ratio / (group_size + 1)) * features

compute_num_basis(100,3,0.9)

22.5

In [82]:
def compute_num_basis(nx, nf, group_strategy, compression_ratio):
    total = nx * nf * group_strategy
    num_basis = (total * compression_ratio) // (nx + nf * group_strategy)
    return int(num_basis)

In [93]:
compute_num_basis(100,1000,1,0.9)

81

In [14]:
compute_num_basis(100,100,2,0.9)

66

In [ ]:
compute_num_basis(100,100,1,0.9)

In [68]:
import torch
A = torch.randn(3, 6)

In [69]:
U, S, Vh = torch.linalg.svd(A, full_matrices=False)

In [43]:
U.shape, S.shape, Vh.shape

(torch.Size([3, 3]), torch.Size([3]), torch.Size([3, 6]))

In [44]:
torch.dist(A, U @ torch.diag(S) @ Vh)

tensor(9.4855e-07)

In [74]:
k = 2
U_k = U[:,:k]
S_k = S[:k]
Vh_k = Vh[:k,:]

In [75]:
torch.dist(A, U_k @ torch.diag(S_k) @ Vh_k)

tensor(0.9563)

In [70]:
(U @ torch.diag(S)).shape

torch.Size([3, 3])

In [71]:
B = U @ torch.diag(S)
C = Vh.clone()

In [72]:
B @ C

tensor([[-2.7860,  0.0633,  0.1788,  1.1016, -0.8312, -0.0152],
        [-1.5974, -0.0145, -0.8706,  0.7203, -0.9590, -0.4208],
        [ 0.0225, -1.4150,  0.2763,  0.8227,  0.5508, -0.1412]])

In [73]:
A

tensor([[-2.7860,  0.0633,  0.1788,  1.1016, -0.8312, -0.0152],
        [-1.5974, -0.0145, -0.8706,  0.7203, -0.9590, -0.4208],
        [ 0.0225, -1.4150,  0.2763,  0.8227,  0.5508, -0.1412]])

In [ ]:
U_k @ torch.diag(S_k) @ Vh_k

tensor([[-2.6527, -0.0723, -0.2512,  1.1536, -0.9690, -0.2129],
        [-1.7942,  0.1856, -0.2354,  0.6435, -0.7555, -0.1286],
        [-0.0109, -1.3810,  0.3842,  0.8097,  0.5853, -0.0915]])

In [77]:
B_k = B[:, :k]
C_k = C[:k, :]

In [78]:
B_k @ C_k

tensor([[-2.6527, -0.0723, -0.2512,  1.1536, -0.9690, -0.2129],
        [-1.7942,  0.1856, -0.2354,  0.6435, -0.7555, -0.1286],
        [-0.0109, -1.3810,  0.3842,  0.8097,  0.5853, -0.0915]])

In [79]:
torch.dist(B_k @ C_k, U_k @ torch.diag(S_k) @ Vh_k)

tensor(0.)

In [80]:

A = torch.randn(7, 4)
U, S, Vh = torch.linalg.svd(A, full_matrices=False)

In [81]:
U.shape, S.shape, Vh.shape

(torch.Size([7, 4]), torch.Size([4]), torch.Size([4, 4]))